# Site settings for development mode
url: https://angulardart-org-dev.firebaseapp.com
# Increment this site-global image URL version number query parameter when you
# need to test og:image updates on a development server (in the absense of
# file fingerprinting).
og_image_vers_dev_only: "?1"
